name: ItemLottery
author: Aurin

main: itemlottery.ItemLottery 
version: 1.0.0

commands:
 setlotterystack:
  description: Sets the stack to give a player upon winning, and how many to give.
  permission: itemlottery.setlotterystack
  usage: Usage: /SetLotteryStack [ITEM] [AMOUNT]
 setlotterychance:
  description: Sets the chance to win on a roll.
  permission: itemlottery.setlotterychance
  usage: Usage: /SetLotteryChance [1-100]
 lotteryinfo:
  description: Shows the current prize, and chances to win.
  permission: itemlottery.lotteryinfo 
  usage: Usage: /LotteryInfo

permissions:
   itemlottery.*:
     description: Gives access to all ItemLottery commands.
     children:
       itemlottery.setlotterystack: true
       itemlottery.setlitterychance: true
       itemlottery.lotteryinfo: true
   itemlottery.setlotterystack:
     description: Sets the stack to give a player upon winning, and how many to give.
     aliases: [set_lottery_stack, setlotteryitem, set_lottery_item]
     default: op
   itemlottery.setlotterychance:
     description: Sets the chance to win on a roll.
     aliases: [set_lottery_chance]
     default: op
   itemlottery.lotteryinfo:
     description: Show the current prize, and chances to win.
     aliases: [lottery_info, lotteryprize, lottery_prize]
     default: true  
   